### ISSUE TITLE
No module named 'video_knet_vis'

### ISSUE THREAD

**Issue by BJUT-AIVBD-1** [lxtGH/Video-K-Net#2]
Thanks for your nice work.

When I tried to train a VPS model in KITTI-STEP dataset, the setting 'custom_imports' [in config/det/base/models/knet_kitti_step_s3_r50_fpn.py] imports lots of python files from 'video_knet_vis' folder, but I can't find the folder in this project.

I renamed folder 'knet' in root path as 'video_knet_vis' and most files can be found except the follows, and a module named 'unitrack' can't be found in many python files.

>     video_knet_vis.det.video_knet_vis
>     video_knet_vis.video.video_knet_vis
>     video_knet_vis.video.knet_track

I'm not sure whether the renaming operation is reasonable and how to install 'unitrack' module. Can you give me some advice?

**Comment by liwensheng2020** [comment]
Thanks for your nice work.

When I tried to train a VPS model in KITTI-STEP dataset, the setting 'custom_imports' [in config/det/_base_/models/knet_kitti_step_s3_r50_fpn.py] imports lots of python files from 'video_knet_vis' folder, but I can't find the folder in this project. 

I renamed folder 'knet' in root path as 'video_knet_vis' and most files can be found except the follows, and a module named 'unitrack' can't be found in many python files.
> video_knet_vis.det.video_knet_vis
> video_knet_vis.video.video_knet_vis
> video_knet_vis.video.knet_track

I'm not sure whether the renaming operation is reasonable and how to install 'unitrack' module. Can you give me some advice?

**Comment by lxtGH** [comment]
Try the new code.
