### ISSUE TITLE
About reproduction of Cityscapes-VPS results

### ISSUE THREAD

**Issue by markusschoen** [lxtGH/Video-K-Net#3]
Hi,

thank you for your awesome work. I'm trying to reproduce your results with R50 backbone on the Cityscapes-VPS dataset. I have some questions about that:
1. You pretrain your network on the Cityscapes image panoptic segmentation dataset first and then use the pretrained model to finetune on the Cityscapes VPS dataset. Is that correct?
2. I tried to train the model on the Cityscapes image panoptic segmentation dataset using your [cityscapes_panoptic config file](https://github.com/lxtGH/Video-K-Net/blob/main/configs/det/_base_/datasets/cityscapes_panoptic.py). However, my training always aborts after the first epoch during evaluation with the following error. Do you have an idea, how to fix this error?
```
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 2550 closing signal SIGTERM
/opt/conda/lib/python3.8/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 20 leaked semaphore objects to clean up at shutdown
```
3. Can you provide your evaluation results (PQ, PQ_th, PQ_st) for the model trained on the Cityscapes image panoptic segmentation dataset evaluated on the default Cityscapes val set? This would help a lot to check, if the pretrained model is good.

**Comment by lxtGH** [comment]
@markusschoen Hi! 

1, Correct.

2, I do not meet such error. Please check your mmcv/mmdet version with pytorch. 

3, The Cityscapes model with R50 is about 61.3 PQ. The code of Cityscape VPS will not be released recently since they are used internally. 
You can checkout this repo for your reference. https://github.com/HarborYuan/PolyphonicFormer

**Comment by markusschoen** [comment]
Thank you! I was able to fix my environment and train a model on the Cityscapes image panoptic segmentation dataset (using 8 GPUs). However, my model only achieves about 56.0 PQ. I'am using the following config
```
_base_ = [
    '../_base_/schedules/schedule_1x.py',
    '../_base_/default_runtime.py',
    '../_base_/models/knet_citystep_s3_r50_fpn.py',
    '../_base_/datasets/cityscapes_panoptic.py',
]


num_proposals = 100
load_from = None

work_dir = 'logger/blackhole'

runner = dict(type='EpochBasedRunner', max_epochs=8)

model = dict(
    type='KNet',
    backbone=dict(
        type='ResNet',
        depth=50,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        frozen_stages=1,
        norm_cfg=dict(type='SyncBN', requires_grad=True),
        norm_eval=True,
        style='pytorch',
        init_cfg=dict(type='Pretrained', checkpoint='torchvision://resnet50')),
    roi_head=dict(
            type='KernelIterHead',
            merge_joint=True,),
    test_cfg=dict(
        rpn=None,
        rcnn=dict(
            max_per_img=num_proposals,
            mask_thr=0.5,
            stuff_score_thr=0.05,
            merge_stuff_thing=dict(
                overlap_thr=0.6,
                iou_thr=0.5, stuff_max_area=4096, instance_score_thr=0.3)))
)

lr_config = dict(
    policy='step',
    warmup='linear',
    warmup_iters=1000,
    warmup_ratio=0.001,
    step=[7, ],
)
data = dict(
    samples_per_gpu=2,
    workers_per_gpu=2,
)
```

I also set `num_thing_classes=8, num_stuff_classes=11, cityscapes=True and kitti_step=False` in `../_base_/models/knet_citystep_s3_r50_fpn.py`.
Is there anything wrong with my config?

**Comment by lxtGH** [comment]
I think you do not use the COCO pretrained model. I will release the Cityscape trained K-Net. Here.

As shown in our paper, we use COCO pretrained model for VPS tasks.

I will put the trained model here. 

The trained model can be downloaded now
