### ISSUE TITLE
About test code for VIS

### ISSUE THREAD

**Issue by wengkai0** [lxtGH/Video-K-Net#7]
Hi Dr Li,

Thanks for your great work! Could I ask how could I get the quantitative results for youtube-vis-2019 dataset? I did not find any test.py file for this part. Could you pls give me some instructions?

Thnaks a lot!

**Comment by lxtGH** [comment]
Hi! I have changed the readme.md.   You should use tools_vis/dist_test_whole_video.sh to generate the json file. Then, update the json file to the youtube-vis-2019 server.
